version: "3.8"
services:
  client:
    image: "kh2fm-randomizer:dev"
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
